# this text based on personal selection and data support

d = {"good": ["I have wavy hair that can be coaxed into curls or dried straight. This hairdryer works for both, and dries quickly whether for curly or for straight hair. The diffuser is wonderful. I can put my hair into it and my hair stays without blowing out of it. I get nice, voluminous curly hair. There is a wide range of  blower strength and heat available for this hairdryer, and for blowdrying straight, I need to use one notch below the maximum for both. Otherwise, my hair blows everywhere. Despite the blower strength, the hair dryer is pretty quiet and fairly light. The cord is nice and long. One last thing--I already knocked this hair dryer off my counter top, and it survived, seemingly without any problems.",
        "This is my only experience with an ionic hair dryer, so I have nothing with which to compare this one.  However, I bought it because I had several expections about its features.  Here is how each feature measured up:<br />Quicker?  NO.  It may even take a little longer than a standard 1875-watt dryer.  The reason is that the fan does not blow very hard.  The high setting blows about like the low setting on a standard dryer.<br />Reduced frizz/flyaways/static? YES.  These are significantly reduced.<br />Increased shine?  YES.  My hair is visibly shinier.<br />Quieter?  YES, but qualified.  The only reason it is quieter is because it doesn't blow air as hard as a regular dryer.<br />Freshens hair?  YES.  <br />Another drawback:  This dryer is very heavy.  It took me several days to get used to how heavy it is.<br />This dryer delivers almost all of what ionic hairdryers promise, but I was mostly hoping for a dryer to speed drying time.  If you have thin hair or hair that dries quickly or have plenty of time to dry your hair, then I would highly recommend this dryer.  My hair looks shinier and healthier.",
        "This hairdryer far exceeded my expection for<BR>volumizing and adding shine.<br />I have limp and fine hair and had tried anything<BR>from volumizing shampoo, hot curlers to mega-hold<BR>hair spray. Nothing was ever so satisfying and lasting as<BR>the results I got from this hair dryer.  I<BR>blow dry as I normally would and my hair looks<BR>bouncy and shiny right away.  And it stays<BR>that way even overnight!  I never thought<BR>this was possible without going to a professional<BR>salon, getting my hair stretched by large brushes and<BR>baked under a blowdryer for 40 minutes.<BR>And there is nothing better than stumbling upon an <BR>inexpensive product that does wonders.<BR>Highly recommended for fine hair.",
        "I have thick shoulder length hair, that usually takes 35 - 40 minutes to dry. With this dryer, I'm done in 20 minutes and my hair looks smooth and soft.  I was skeptical about the whole ionizing thing, but it has made a big difference with my hair.  The removable<BR>filter was the deciding factor.  I've thrown away dryers just because I couldn't clean them. Excellent product!",
        "As a child of the Sixties, I still wear my hair long and I blow it dry every morning. When my old Hartman Protech 1600 hair dryer hit the bathroom floor, things weren't the same. Eventually, in a spectacular pyrotechnic display, it breathed its last.<br />Since I had paid 20 bucks for it way back when, I was ready to spend that much on a replacement. Much to my surprise, in the 10 or so years I'd owned that dryer, a lot had changed, and now the same money buys a lot more hair dryer, so with some dough to spare, I bought one of these.<br />Many complain that it doesn't pack the same wallop as other dryers but that's a case of perception versus reality. The Conair's barrel has a larger diameter than most dryers and its fan is quieter, so while the perceptible breeze isn't as blustery, it's still moving plenty of air. I know because I use an egg timer to count off 3 minutes while I dry my hair and the Conair never leaves my hair damp (a barber told me that after 3 minutes of blow drying, you're just toasting your hair and not helping it). If you MUST have that scalp-scorching pinpoint blast, Conair includes a concentrator.<br />Ions are all the rage in hair dryer technology right now. Purportedly, a stream of ions directed at your hair will neutralize static electricity and smooth out frizzy hair. Ions are also claimed to flatten out scaly hair shafts, resulting in more shine. I'm waiting for our good friends at Consumer Reports to weigh in on the benefits (or lack thereof) of dual ion ports, but after a week of daily use with the ion switch ON, I've noticed that my hair doesn't fight me as much when I brush it into place. Even when the static-charged Santa Ana winds are howling through sunny SoCal, my hair doesn't stick out like porcupine quills. And, yes, if I turn my head from side to side, there's a noticeable shimmer that either wasn't there before or I had never noticed it.<br />A minor flaw is that the power and ion switches respond to a very light push, but after a couple uses you learn to position your hand accordingly after switching on the dryer. The dryer offers low and high air-speed/heat settings and has a cool shot button that cuts off the heater while cranking the fan up to its fastest speed. Cool shot is another feature that is said to set a style in place by cooling down the hair quickly.<br />So, whether ions really do or don't make a difference, the overall performance of the Conair Ion Shine is worth the price.ut after a couple uses you learn to position your hand accordingly after switching on the dryer. The dryer offers low and high air-speed/heat settings and has a cool shot button that cuts off the heater while cranking the fan up to its fastest speed. Cool shot is another feature that is said to set a style in place by cooling down the hair quickly. <br />So, whether ions really do or don't make a difference, the overall performance of the Conair Ion Shine is worth the price.",
        "I wish I could have read reviews on this product before I bought it.  <br />It was very difficult to put back into its case.  <br />I only used it a few times. The last time it just shut off and never would start again. I would not recommend this product.",
        "When I first saw this model I was excited about the practicality of it's wall mount design, and the sleek styling it offered.  It's 1600 watts supplied ample drying power, and the unit even has the ability to be shut off from the handset... a feature I am very fond of!  The problem; they don't last!  My first one lasted about 9 months and then began to continually overheat and shut off several times during my styling process.  Blowing into the back got old pretty quick, and in the hope that I just got that one lemon, I decided to order another.  I've owed my present unit for not quite a year now, and a few days ago I went to turn it on, and it just wouldn't.  Terminal.  I find myself again in need of a new wall mounted hair dryer, dreading removing this one and remounting the next.  I'm presently seeking a better made model, after all, if you're going to mount something on your wall, you want it to last more than a year, no?",
        "Ordered this product without reading other reviews first.  Wish I had because these ladies are dead on.  The dryer cuts off as soon as it starts to get hot.  Don't waste your time or money.  It's Saturday.  My hair is wet and set, and I'm left without a dryer.  I've tried three times: twice on high and once on medium setting.  I'm sending this back right away.  Amazon don't let Conair blame this on you.  This model is DEFECTIVE!",
        "Pros:   <br />1. This blow dryer is great for the price.  Just don't expect a $100+ ionic dryer.  You get a nice $18 dryer for $18 - simple. <br />2. Nice looking, sleek design, with retractable cord.  This is not a compact dryer for travel - it should be considered more of a mid-size. <br /> <br />Cons: <br />1.  Retractable cord is quite short, which could be a problem if your outlet is not very close by.   <br />2.  Very loud!  I saw others complain about this, and now I know what they mean.  It's loud.  <br />3.  The retractable cord failed to retract after a couple of uses.  This is disappointing considering it was a major factor in my purchase. <br /> <br />Bottom Line: <br />Does it dry hair quickly and make it smooth and silky??  No more than any other dryer.  It's a nice, inexpensive, blow dryer, but I personally would not purchase it again. <br />",
        "I had wanted a hair dryer for xmas which I got. I was so happy that way I didn't have to be under a hooded hair dryer. Well every time I have used it and it's not many, I put the hair dryer on medium heat and it will be okay for a couple of minutes, 5 minutes and automatically shut off. What the hell. Now I have curlers in my hair and this thing decides to shut off when it feels like. This is going straight back to the store. This is the worst hair dryer.  <br />                    Signed wet hair."]
,
"bad": ["bought it. didn't use it. wanted a silver one. picture looks silver. returned it. will get exactly what i want instead.",
        "My wife LOVES this blow dryer so much that she wanted me to buy one for our daughter too! Excellent price for excellent product!",
        "My hair is curly, so I think this dryer is not so stronger for my hair.",
        "cute and stylish", "very much, worth it",
        "not good", "it suddenly can't turn on days ago", "excellent hair dryer", 
        "no warm setting can't 'use",
        "I made this order. after i got it, i found out it wasn't working. i plugged it & it refused to come on. it was a pure waste of my money because what's the point if i can't use it. i should have gotten something better or more mature. Now i regret buying it."]
}